### ISSUE TITLE
[Error] Installation did not complete within expected timeframe.

### ISSUE THREAD

**Issue by sheriffed3** [GalacticFog/gestalt-k8s-install#4]
Hi,
Help please to resolve issue.

$ sudo ./install-gestalt-platform docker-for-desktop.conf
_...(removed)_
Running post-install: docker-post-deploy.sh ...

Waiting for Gestalt Platform installation to complete
........................................................................................................................................................................................................
[Error] Installation did not complete within expected timeframe.

File diagnostics.log is attached.
[diagnostics.log](https://github.com/GalacticFog/gestalt-k8s-install/files/2177574/diagnostics.log)

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

Sure, do you also have a `gestalt-installer.log` file?  If so, could you please provide that?  The installation runs an installation container, and the output from that container is written to `gestalt-installer.log`, which may indicate the error.

Also, you shouldn't need 'sudo'.  Is there a specific reason you're using 'sudo' when running the installer?

**Comment by sheriffed3** [comment]
Hi @eric-sonchaiwanich, 
1. Installer.log is attached. I see that trouble is to connect to the database but I can't find gestalt-postgresql's log to investigation. Status of the container gestalt-postgresql is "Pending"

[gestalt-installer_gestalt-system_gestalt-installer-0fa0f4dc975b36300ca46f4b5f863d45aa0e1f1c86f3ce66c4a21254fd23fe33.log](https://github.com/GalacticFog/gestalt-k8s-install/files/2179136/gestalt-installer_gestalt-system_gestalt-installer-0fa0f4dc975b36300ca46f4b5f863d45aa0e1f1c86f3ce66c4a21254fd23fe33.log)

2. I have used "sudo" because I got error without this one.
`Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/images/create?fromImage=galacticfog%2Fgestalt-installer&tag=release-2.1.0: dial unix /var/run/docker.sock: connect: permission denied
[Error] Error pulling docker image, installation cannot continue.`

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

OK, I think there are a few things:

1. I suspect the postgres database container doesn't have access to a persistent volume, which is preventing the database Pod from being created.  On a 'Docker for desktop' Kubernetes installation, the installer attempts to create a hostpath volume for the postgres database.  

We could verify if a volume is present - could you provide the output from the following commands:  

```
kubectl get pv

(There should be a volume with status `Bound` and claim should be `gestalt-system/gestalt-postgresql`)

kubectl get pvc --all-namespaces

(This should also show status `Bound`)
```

Here's the output from a working system:
```
$ kubectl get pv
NAME                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                               STORAGECLASS   REASON    AGE
hostpath-volume-breakqvs   100Mi      RWO            Delete           Bound     gestalt-system/gestalt-postgresql   hostpath                 10d


$ kubectl get pvc --all-namespaces
NAMESPACE                              NAME                                                STATUS    VOLUME                     CAPACITY   ACCESS MODES   STORAGECLASS                                        AGE
gestalt-system                         gestalt-postgresql                                  Bound     hostpath-volume-breakqvs   100Mi      RWO            hostpath                                            10d
```

2. I see you're using the `docker-for-desktop.conf` configuration file with the installer.  That configuration file assumes that Kubernetes is present at `localhost`.  I see that your Kubernetes instance is at `192.168.100.113`, and appears to be a one node cluster.  Could you tell me what Kubernetes distribution you're using?

You will need to create a custom install config file for your environment.  You could modify the `docker-for-desktop.conf` file and set 
 - `external_gateway_host=192.168.100.113`, and 
 - `gestalt_ui_ingress_host=192.168.100.113`

Depending on what storage is available, there are other parameters that may need to be changed:
 - `internal_database_pv_storage_class="hostpath"`


If you'd like to see the logs for the postgres container, here're some useful commands:
```
kubectl get pod -n gestalt-system

(find the pod name, then run the following command with the exact pod name)

kubectl logs -n gestalt-system gestalt-postgresql-XXXXXX
```

As for needing "sudo" to access Docker, you could try running these commands to allow a non-root user to use Docker.
```
  sudo groupadd docker
  
  sudo usermod -aG docker $USER
  
 (log out, log in)
```

Let me know how it goes, and I'd be happy to help you troubleshoot on a live screenshare session if you prefer - let me know.

Thanks,
Eric

**Comment by sheriffed3** [comment]
Hi @eric-sonchaiwanich ,
`$ kubectl get pv`
`No resources found.`

`$ kubectl get pvc --all-namespaces`
`NAMESPACE        NAME                 STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE`
`gestalt-system   gestalt-postgresql   Pending                                       hostpath       7m`


`$ kubectl version`
`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}`

File docker-for-desktop.conf is attached

[docker-for-desktop.conf.txt](https://github.com/GalacticFog/gestalt-k8s-install/files/2184973/docker-for-desktop.conf.txt)

When I used 192.168.100.113 I have got error:
`Installing Gestalt Platform to Kubernetes using Helm...
Command: helm install --namespace gestalt-system ./gestalt -n gestalt -f gestalt-config.yaml
Error: release gestalt failed: Ingress.extensions "gestalt-ui" is invalid: spec.rules[0].host: Invalid value: "192.168.100.113": must be a DNS name, not an IP address"`
I'm using DNS name within config file and file /etc/hosts consists name "ip-192-168-100-113"

**Comment by sheriffed3** [comment]
Status of gestalt-system
`$ kubectl get pods --namespace gestalt-system`
`NAME                                  READY     STATUS             RESTARTS   AGE`
`gestalt-elastic-6fbf6cb49f-bf2vv      1/1       Running            0          34m`
`gestalt-installer                     1/1       Running            0          34m`
`gestalt-meta-75c4db7d7d-wfpr8         0/1       CrashLoopBackOff   10         34m`
`gestalt-postgresql-59755bc567-xswdn   0/1       Pending            0          34m`
`gestalt-rabbit-77856db4b9-6hvjm       1/1       Running            0          34m`
`gestalt-security-5c965d65b6-nfnv7     1/1       Running            0          34m`
`gestalt-ui-6f4989974c-8gpcv           1/1       Running            0          34m`

**Comment by eric-sonchaiwanich** [comment]
OK, the cluster doesn't appear to have dynamic provisioning for hostpath volumes.  You could try another storageclass if you know what your environment supports, or you could try to create a persistent volume (PV) manually.  Some Kubernetes environments (but not all) can list the storage classes available to you via `kubectl get sc`.

Here's an example to create a hostpath PV manually:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-volume-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mnt/hostpath-volume-1
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
EOF
```

For reference, if you want to use another volume type (an NFS or EBS volume for example), these documentation links are helpful:
https://kubernetes.io/docs/concepts/storage/volumes/
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

Regarding the DNS name, I made a mistake with your configuration.  Let's try:
```
external_gateway_host="ip-192-168-100-113"
gestalt_ui_ingress_host="ip-192-168-100-113"
```
If that doesn't work, we can try a different /etc/hosts entry:
```
  (in /etc/hosts)
  192.168.100.113	gestalt-host

  (in gestalt config file)
  external_gateway_host="gestalt-host"
  gestalt_ui_ingress_host= "gestalt-host"
```

FYI, if the Gestalt environment needs to be accessible via an external DNS name, then the workflow is usually to set up the external DNS name for a Load Balancer that fronts the Kubernetes worker nodes.  Then use the external DNS name in the Gestalt configuration file.

Also, could you share the commands or instructions you used to set up Kubernetes?  It would be helpful to know what vendor provided Kubernetes, e.g. is it Canonical's distribution of Kubernetes (CDK).

**Comment by sheriffed3** [comment]
Hi @eric-sonchaiwanich ,
I created manually `pv` and `Gestalt Platform installation complete!` Thank you!
But I have got error when tried to connect to the Web-UI. Screenshot is attached.

![gestalt_error](https://user-images.githubusercontent.com/31288168/42629406-e36e01c0-85db-11e8-8b65-aca4078ccf66.png)

About Kubernetes:
The repository was added to the apt source.list
`deb http://apt.kubernetes.io/ kubernetes-xenial main `

After that kubernetes was installed:
`apt-get update`
`apt-get install -y kubelet kubeadm kubectl kubernetes-cni`

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

Which browser are you using?  I'm not sure what is happening there - we'd have to gather some information to troubleshoot.  Here are some troubleshooting steps:

First, try to login with the CLI.  From the `gestalt-k8s-install` directory, run the following:
```
./fog login http://ip-192-168-100-113:31112
```

If you're able to login correctly, then try to refresh the UI in the browser and try again.  Also, try another browser if possible.

Next, try clearing your browser cookies.  Specifically there's a cookie called `auth_token` - try deleting that and then refresh the browser UI.

Next, try viewing the pod logs for errors:
```
# Get pod names, and ensure pods are running and not crashing or pending
kubectl get pod -n gestalt-system

# Get logs for UI - save to ui.log
kubectl log -n gestalt-system gestalt-ui-XXXXXXXXXX > ui.log

# Or tail the log
kubectl log -n gestalt-system gestalt-ui-XXXXXXXXXX --follow

# Check for Errors in Meta.  Specifically check for signs that it is communicating with Postgres properly
kubectl log -n gestalt-system gestalt-meta-XXXXXXXXXX > meta.log

# Check for Errors in Security
kubectl log -n gestalt-system gestalt-security-XXXXXXXXXX > security.log
```

From there, if there is an error in one of the `gestalt-*` pods, you could try to delete that pod (another pod should be re-created automatically to replace it), and try to login via the browser again.  To delete a pod, the command is:
```
kubectl delete pod -n gestalt-system gestalt-ui-XXXXXXXXX
```

Hope that helps, let me know how it goes. Also, feel free to provide the logs and I will review them.

Thanks,
Eric

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

I suspect we introduced an issue that has disabled the use of the UI over HTTP.   That is the likely case of the "unknown error" you're seeing.  I'm checking with team but it looks like we'll need to push an update to make HTTPS work for installs that don't have a Load Balancer fronting the kubernetes nodes (which would normally terminate SSL for HTTPS).  Will keep you posted.

Thanks,
Eric

**Comment by sheriffed3** [comment]
Hi @eric-sonchaiwanich ,
Thank you.
I found that DNS-name also can introduces problem.
`10:32:57.262 |-ERROR| KubernetesService: error creating Kubernetes Ingress for container 754ac415-2119-4cfd-b83c-0e97110346db; assuming that it was not created
skuber.api.client.package$K8SException:` `Status(v1,Status,ListMeta(,),Some(Failure),Some(Ingress.extensions "kng" is invalid: spec.rules[0].host: Invalid value: "ip-192-168-100-113:31113": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-
9]*[a-z0-9])?)*')),`
`Some(Invalid),Some({"name":"kng","group":"extensions","kind":"Ingress","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"ip-192-168-100-113:31113\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"spec.rules[0].host"}]}),Some(422))`

I changed DNS-name within /etc/hosts to gestalt.local and reinstalled gestalt
`$ ./fog login http://gestalt.local:31112`
`? Username admin`
`? Password [hidden]`
`Logging in to http://gestalt.local:31112...`
`Authenticated. User admin logged in to http://gestalt.local:31112.`

But I still get unknown error in the browser. I'm looking forward your update.
Thank you!

**Comment by sheriffed3** [comment]
And one more. May be your script will checks parameter vm.max_map_count? Reason - if this parameter less than 262144 your container gestalt-elastic-XXXXX can't start.

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

I believe we've fixed the problem.  You can either re-install Gestalt, or you could just update the Gestalt UI container with the following commands:

```
# Get pod names
kubectl get pod -n gestalt-system

# Delete Gestalt-UI pod.  A new one will be recreated in its place
kubectl delete pod -n gestalt-system gestalt-ui-XXXXXXXXXX
```

A new Gestalt UI pod should be created in its place, and the latest `galacticfog/gestalt-ui-react:release-2.1.0` docker image should be automatically pulled (since `imagePullPolicy: Always` is set on the `gestalt-ui` Deployment resource.

The issue is that we were enforcing the use of HTTPS/SSL at the container level, but this introduced a problem for deployments where HTTPS/SSL is not in place - typically environments with no external load balancer used.

Please let me know if this solution works for you, and thank you for the tip on the `gestalt-elastic-XXXX` container, we'll address that separately.

Thanks,
Eric

**Comment by eric-sonchaiwanich** [comment]
Hi @sheriffed3,

Just following up. Were able to re-try and get the installation to complete successfully?

Thanks,
Eric

**Comment by sheriffed3** [comment]
Oh sorry! 
I leave for two weeks.

Отправлено с iPhone

**Comment by sheriffed3** [comment]
Hi @eric-sonchaiwanich ,
Thank you!
This solution works for me!

**Comment by eric-sonchaiwanich** [comment]
@sheriffed3 Great! Thank you for confirming, appreciate you working with me to get this resolved.
